<Project>
  <Target Name="CopyPackageTranslationFiles" AfterTargets="Build">
    <Message Text="Copying translation files: $(MSBuildProjectName)" Importance="high" />
    <Copy
      SourceFiles="@(PackageTranslationFiles->'%(FullPath)')"
      DestinationFolder="Localization\%(PackageTranslationFiles.RecursiveDir)"
      Condition="'@(PackageTranslationFiles)' != ''"
      SkipUnchangedFiles="true"
      OverwriteReadOnlyFiles="false" />
  </Target>
</Project>
